// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SammourProfile.Data;

#nullable disable

namespace SammourProfile.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SammourProfile.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("SammourProfile.Models.Expertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expertises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "Sep 2022",
                            Description = "I started studying Web developer at TUC Yrkeshögskola and is expected to finish in Jun 2024:  (Design & UX)-(HTML & CSS)-(C#)-(ASP Net Core)-(JavaScript)-(DataBase)",
                            Field = "Web developer"
                        },
                        new
                        {
                            Id = 2,
                            Date = "Jun 2022",
                            Description = "I finished studying General course - IT / Web (Web development) at Mullsjö Folkhögskola.",
                            Field = "Web development"
                        },
                        new
                        {
                            Id = 3,
                            Date = "Sep 2020",
                            Description = "I moved to live in Sweden (New culture - New Challenges)",
                            Field = "Move to Sweden"
                        },
                        new
                        {
                            Id = 4,
                            Date = "Okt 2017",
                            Description = "I started working in Dar Amman Academy, Jordan (Organize training and academy events or workshops, Manage and organize databases, Handle correspondence, complaints and questions, Supervise the work of the administrative staff.)",
                            Field = "Administrativ assistant"
                        },
                        new
                        {
                            Id = 5,
                            Date = "May 2017",
                            Description = "I started working as a freelancer on several platforms: Data entry/Designing with Illustrator and Photoshop programs/Translating reports and writing research",
                            Field = "Web Freelancer"
                        },
                        new
                        {
                            Id = 6,
                            Date = "Okt 2016",
                            Description = "I started working in West America University (Regional Office), Jordan (Plans, organizes, maintains, develops and manages admissions and registration services processes and functions.)",
                            Field = "Head of Admissions and Registration"
                        },
                        new
                        {
                            Id = 7,
                            Date = "Jun 2015",
                            Description = "I started working in Consulting institution, Jordan (Organize meetings, corporate events, conferences and manage databases, Handle correspondence, complaints and questions, Supervise the work of the administrative staff, Design advertising and brochures for the company)",
                            Field = "Administrativ assistant"
                        },
                        new
                        {
                            Id = 8,
                            Date = "Sep 2015",
                            Description = "Graphic design (Photoshop, Illustrator)",
                            Field = "Graphic design"
                        },
                        new
                        {
                            Id = 9,
                            Date = "Jun 1994",
                            Description = "I finished studying Chemical Engineering in Jordan University, Jordan",
                            Field = "B.Sc. Chemical Engineering"
                        },
                        new
                        {
                            Id = 10,
                            Date = "1994-2008",
                            Description = "Matematik och naturvetenskap lärare, Labbarbetare, Kemiingenjör",
                            Field = "Various previous jobs"
                        });
                });

            modelBuilder.Entity("SammourProfile.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C# is a simple & powerful object-oriented programming language developed by Microsoft. C# can be used to create various types of applications, such as web, windows, console applications, or other types of applications using Visual studio.",
                            ImageURL = "/images/C-Sharp.png",
                            Name = "C-Sharp"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Structured Query Language (SQL) is a standardized programming language that is used to manage relational databases and perform various operations on the data in them.",
                            ImageURL = "/images/SQL.png",
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 3,
                            Description = "HTML (HyperText Markup Language) is the most basic building block of the Web. It defines the meaning and structure of web content.",
                            ImageURL = "/images/HTML.png",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cascading Style Sheets (CSS) is a style sheet language used for describing the look and formatting of a document written in a markup language. CSS3 is a latest standard of css earlier versions(CSS2).",
                            ImageURL = "/images/CSS.png",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 5,
                            Description = "ASP.NET Core MVC is a rich framework for building web apps and APIs using the Model-View-Controller design pattern. The Model-View-Controller (MVC) architectural pattern separates an application into three main groups of components: Models, Views, and Controllers.",
                            ImageURL = "/images/ASPNET.png",
                            Name = "ASP.NET Core MVC"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Entity Framework Core (EF Core) is an open-source, lightweight, and cross-platform version of Entity Framework data-access technology. It is an Object-Relational Mapper (ORM) tool that enables developers to work with relational databases using .NET objects.",
                            ImageURL = "/images/EF.png",
                            Name = "Entity Framework (EF) Core"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
